server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8889
  rootPath: /api

logging:
  level: INFO
  loggers:
    com.campspot: DEBUG

redis:
  host: localhost
  port: 6379
